idci_keycloak_security:
  #server_url: '%env(resolve:KEYCLOAK_SERVER_BASE_URL)%/auth'
  server_public_url: "%env(resolve:KEYCLOAK_SERVER_PUBLIC_BASE_URL)%/auth"
  server_private_url: "%env(resolve:KEYCLOAK_SERVER_PRIVATE_BASE_URL)%/auth"
  realm: "%env(resolve:KEYCLOAK_REALM)%"
  client_id: "%env(resolve:KEYCLOAK_CLIENT_ID)%"
  client_secret: "%env(resolve:KEYCLOAK_CLIENT_SECRET)%"
  default_target_path: "/api/products"
  ssl_verification: true
