security:
  enable_authenticator_manager: true

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: id
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      custom_authenticators:
        - App\Security\KeycloakAuthenticator
    api:
      pattern: ^/api
      lazy: true
      provider: app_user_provider
      custom_authenticators:
        - App\Security\KeycloakAuthenticator

  access_control:
    - { path: ^/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api, roles: ROLE_OFFLINE_ACCESS }
